### ISSUE TITLE
Randomize seed button no longer generates batches of images

### ISSUE THREAD

**Issue by aethere92** [Kilvoctu/aiyabot#144]
**Describe the bug**  
After fetching latest, the randomize seed button no longer seems to take into account if the original prompt contained batches in it and only randomizes the last image generated. 

My guess is this is because the bot now seems to send a separate message for each generated image (I guess this has something to do with the new context menu, which doesn't seem to be usable on a single image (e.g. if you try to use it in a message containing multiple images it will generate the info for each of them individually)).

I'm not sure if this is an actual bug or intended functionality. Personally, I was using the generate randomize button with batches far more than I think I will use the new context menu so perhaps if there isn't a way to have both of them work properly allow the user to select? Just throwing ideas. 

---

**Environment**
 - OS: [e.g. Windows / Linux] Windows 11

**Comment by Kilvoctu** [comment]
Heya, this is intentional behavior. Sorry for the change, while I lurk in a number of servers that use the aiyabot (sometimes on my alt), none of them use the batch feature so I dunno much about how it's used 👀
  
Anyway, I pushed an update cbcd3dcddc66a868009bb1d66c9291f14e28f123 to allow continuing usage of batches with the buttons.  

When you launch the aiyabot, she'll add `batch_buttons = "False"` to the config.toml. Change it to `batch_buttons = "True"`, then /settings -> refresh, and the buttons should work like before.  👍

**Comment by aethere92** [comment]
Hey, did a quick test and it seems to work now after the change.
Thanks a lot for the quickly reply and fix

**Comment by Kilvoctu** [comment]
No problem. When people leave feedback, I'm happy to respond with something if it makes sense to me. 👍

A lot of the extra options recently added into config.toml was because I checked out an aiyabot fork and saw the changes they made, then thought, "Hmm, I should really make these as options 🤔"
