### ISSUE TITLE
hires-fix doesn't work

### ISSUE THREAD

**Issue by dejl** [Kilvoctu/aiyabot#169]
Using latest version of aiyabot from this repo
Hiresfix is set to the right upscaler (esrgan4x), but it seems to have no effect on the output image
the output' image is still 512x768, and looks horrible.

"strength" doesn't seem to make any difference

---

**Environment**
 - OS: Linux

---

**Console logs**  
no errors

**Comment by dejl** [comment]
Okay, I updated the code to this, and it works better at least for my purposes.. It would be great to have all this configurable.

```python

 highres_payload = {
               "enable_hr": True,
               "hr_upscaler": queue_object.highres_fix,
               "hr_scale": 2,
               "hr_second_pass_steps": queue_object.steps,
               "denoising_strength": queue_object.strength
               }
```

Thanks!

**Comment by Kilvoctu** [comment]
Heya, AIYA supports legacy high-res fix only.  
https://github.com/Kilvoctu/aiyabot/wiki/Frequently-asked-questions-and-other-tips-(setup)#highres-fix-does-nothing  

I don't intend to implement the new high-res fix, because it allows users to exceed the max_size restriction.  
e.g., max_size set to 1024. User does hr fix at 2x at max size. Now the task is 4x as expensive.  
This is why the scale is kept at 1. Legacy high-res fix works by generating the image at a lower resolution, then upscaling to the user-selected parameter at half the user-selected steps.

If it works for you, you can fork the repo with those changes. Then mark the fork something like "New highres fix method", and I can direct people to it if they want to do it that way.
