### ISSUE TITLE
Note of appreciation

### ISSUE THREAD

**Issue by philpax** [Kilvoctu/aiyabot#18]
Hey there! Would've put this in a GH discussion but those aren't enabled for forks by default.

Just wanted to say I appreciate you setting up a bot to work against a1111's UI - we (friends and I) can now collaborate like we do with Midjourney, and use the web UI when we need more control. This is a huge workflow improvement for us, thank you :)

**Comment by Kilvoctu** [comment]
lol, I did consider enabling discussions, but it's a small project so sending messages as "issues" is all right with me (and I didn't even have "issues" enabled at first 🤦‍♀️)

From the start, I wanted a Discord bot for my group as well. It's fun and quick to play around with. For us, harubaru's bot is the best. It's got slash commands, I like how the outputs are presented, and I like the developer himself, too. He's behind the waifu diffusion model and is the type who is like, "I'm doing all of this for fun".

Anyway, later on, saw everyone talking about a1111's UI and after trying it out, I thought "Wow, I really want the bot to work with this UI".
I started with no Python experience, but with at least *some* technical background I was able to bang sticks and rocks together to get something working. Figured maybe someone else might like it, so pushed initial commit 42f91a773979b3b94a8786f993594db0b997d987, which apparently was only two weeks ago.

Glad some people are making use of the bot 👍

**Comment by Kilvoctu** [comment]
Since I opened up GH Discussions if for some reason people want to use it 😅, I'll go ahead and close this.

I really appreciate the encouragement and all the help; AIYA would have been considered completed a while ago, but everyone here has motivated me to continue.
Also, I am still actively trying to implement #19. There's a large rift in knowledge to bridge that I didn't expect to see; sorry it's taking so long. Each of these random other features I'm adding is slowly accumulating knowledge.
