### ISSUE TITLE
Bot doesn't work in dms

### ISSUE THREAD

**Issue by Jake36921** [Kilvoctu/aiyabot#193]
/draw and other commands doesn't show up or work whenever it's in dms

**Comment by Kilvoctu** [comment]
Heya, this is intentional. It's not a bug . While I may change my mind later on, I don't plan on allowing the aiyabot to work in DMs currently (too many issues in regards to it).  

If you'd like to fork the project and allow DM usage, look in the files for anywhere that says `, guild_only=True` and remove it.
https://github.com/Kilvoctu/aiyabot/blob/6a0ec55fd6a3261d29193ccf9ed767dc43094692/core/stablecog.py#L35
