### ISSUE TITLE
[Bug]"checkpoint not found; loading fallback..." when clicking on the dice icon.

### ISSUE THREAD

**Issue by crckdns** [Kilvoctu/aiyabot#67]
running the "latest" version
```
$ git show
commit 4c00670a66125ad51867fdeeef529dff47d3261f (HEAD -> main, origin/main, origin/HEAD)
Merge: 324f040 3354781
Author: Kilvoctu <kilvoctu@zoho.com>
Date:   Thu Nov 24 15:42:02 2022 -0600

    Merge pull request #66 from Kilvoctu/add-facefix-to-upscale

    Add facefix options to upscalecog
```

after generating some picture with bot via /draw I click on the randomize seed icon under the picture, the bot tries to load some default checkpoint it seems, which my A1111 does not have.
so the A1111 console throws "error":
`Checkpoint  not found; loading fallback modernDisney-v1.1.ckpt [c6303f9f]`

after that the generation works fine, but stays on that model and when I change it back in the A1111 webui to sd1.5 and generate and then click on randomize, the problem repeats.

ps: when trying to select a model in the /draw request, it shows only "Default"

**Comment by Kilvoctu** [comment]
You are just using default models.csv (in the repo's /resources folder), or did you customize it with additional checkpoints?

**Comment by Kilvoctu** [comment]
I pushed an update that may fix the issue you're having, if it's what I think it is. 
db2b519e47db39501128b79e699871c201c8e9af

> ps: when trying to select a model in the /draw request, it shows only "Default"

In regards to this, aiya will not automatically pull in the checkpoints from your web ui. This is intentional. 
You have to fill in the entries manually; I have instructions at the [wiki](https://github.com/Kilvoctu/aiyabot/wiki/Model-swapping). I know it's tedious, I haven't thought of any better way for user to handle setting up checkpoints. 😅
