### ISSUE TITLE
support for embeddings and hypernetwork?

### ISSUE THREAD

**Issue by nicolai256** [Kilvoctu/aiyabot#79]
is it possible to support textual inversion embeddings and hypernetworks? thanks

**Comment by Kilvoctu** [comment]
Embeddings already work if you know what embeddings are present on your Web UI. AIYA simply sends a request to Web UI, so if the prompt contains an embedding then Web UI will recognize it.
There's no direct API support but I can probably find a way to pull list of embeddings from Web UI 🤔

As for hypernetworks, should be possible I think. There are API endpoints for it that seem easy to use hypothetically. Now the issue is that I've never used hypernetworks or know anything about them, so I'll need to learn how to use these things before able to implement and test.

I'll look into these after the holidays.

**Comment by Kilvoctu** [comment]
Heya, I added these features, you can see the details of what I did described in PR #80. 
Basically, embeddings are listed in /tips, and hypernetworks are an additional option for /draw

It all seems to work on my end, but if you find any bugs or such feel free to follow-up 👍

Thanks for the suggestion, hypernetworks are pretty neat lol.
